services:
  - type: web
    name: tramite-documentario
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: your_db_host
      - key: DB_NAME
        value: municipalidad_ml
      - key: DB_USER
        value: your_db_user
      - key: DB_PASS
        value: your_db_password
      - key: SMTP_HOST
        value: your_smtp_host
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: your_smtp_user
      - key: SMTP_PASS
        value: your_smtp_password
      - key: SMTP_FROM
        value: notificaciones@tudominio.com
