services:
  - type: web
    name: tramite-documentario
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: mysql-1c56752d-augustomorimaldonado-758e.l.aivencloud.com
      - key: DB_PORT
        value: "22472"
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
